
server:
  port: 8888

spring:
  freemarker:
    request-context-attribute: req
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    charset: UTF-8
    settings:
      number_format: '0.##'
  mvc:
    static-path-pattern: /static/**