package com.calculator.customer.dao.domain;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.username
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.content
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.user_time
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    private Double userTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.create_time
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.username
     *
     * @return the value of record.username
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.username
     *
     * @param username the value for record.username
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.content
     *
     * @return the value of record.content
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.content
     *
     * @param content the value for record.content
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.user_time
     *
     * @return the value of record.user_time
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public Double getUserTime() {
        return userTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.user_time
     *
     * @param userTime the value for record.user_time
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public void setUserTime(Double userTime) {
        this.userTime = userTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.create_time
     *
     * @return the value of record.create_time
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.create_time
     *
     * @param createTime the value for record.create_time
     *
     * @mbg.generated Mon May 25 12:20:51 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}